services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=petch2541
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
